### ISSUE TITLE
Error during python setup.py install: Invalid version: 'ibl_1.4.2'.

### ISSUE THREAD

**Issue by shunnnli** [int-brain-lab/pykilosort#13]
Hi, I'm trying to install pykilosort in the spikeinterface environment, I've done the following steps successfully, but encountered problem when trying to run `python setup.py install`. Thanks in advance for your help!!

Things that I've run successfully:
1. `pip install cupy`
2. `pip install phylib, pypandoc`
3. `git clone --branch ibl_prod https://github.com/int-brain-lab/pykilosort`
4. `cd pykilosort`
5. `pip install -r requirements.txt`

(spikeinterface) C:\Users\sabatini\Documents\SpikeInterface\pykilosort>python setup.py install
C:\Users\sabatini\.conda\envs\spikeinterface\lib\site-packages\setuptools\dist.py:520: SetuptoolsDeprecationWarning: Invalid version: 'ibl_1.4.2'.
!!

        ********************************************************************************
        The version specified is not a valid version according to PEP 440.
        This may not work as expected with newer versions of
        setuptools, pip, and PyPI.

        By 2023-Sep-26, you need to update your project and remove deprecated calls
        or your builds will no longer be supported.

        See https://peps.python.org/pep-0440/ for details.
        ********************************************************************************

!!
  self._validate_version(self.metadata.version)
running install
C:\Users\sabatini\.conda\envs\spikeinterface\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
C:\Users\sabatini\.conda\envs\spikeinterface\lib\site-packages\setuptools\_distutils\cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
C:\Users\sabatini\.conda\envs\spikeinterface\lib\site-packages\setuptools\command\egg_info.py:131: SetuptoolsDeprecationWarning: Invalid version: 'ibl_1.4.2'.
!!

        ********************************************************************************
        Version 'ibl_1.4.2' is not valid according to PEP 440.

        Please make sure to specify a valid version for your package.
        Also note that future releases of setuptools may halt the build process
        if an invalid version is given.

        By 2023-Sep-26, you need to update your project and remove deprecated calls
        or your builds will no longer be supported.

        See https://peps.python.org/pep-0440/ for details.
        ********************************************************************************

!!
  return _normalization.best_effort_version(tagged)
Traceback (most recent call last):
  File "C:\Users\sabatini\Documents\SpikeInterface\pykilosort\setup.py", line 39, in <module>
    setup(
  File "C:\Users\sabatini\.conda\envs\spikeinterface\lib\site-packages\setuptools\__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\sabatini\.conda\envs\spikeinterface\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\Users\sabatini\.conda\envs\spikeinterface\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\sabatini\.conda\envs\spikeinterface\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\sabatini\.conda\envs\spikeinterface\lib\site-packages\setuptools\dist.py", line 1244, in run_command
    super().run_command(command)
  File "C:\Users\sabatini\.conda\envs\spikeinterface\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\sabatini\.conda\envs\spikeinterface\lib\site-packages\setuptools\command\install.py", line 80, in run
    self.do_egg_install()
  File "C:\Users\sabatini\.conda\envs\spikeinterface\lib\site-packages\setuptools\command\install.py", line 129, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\sabatini\.conda\envs\spikeinterface\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\sabatini\.conda\envs\spikeinterface\lib\site-packages\setuptools\dist.py", line 1244, in run_command
    super().run_command(command)
  File "C:\Users\sabatini\.conda\envs\spikeinterface\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.ensure_finalized()
  File "C:\Users\sabatini\.conda\envs\spikeinterface\lib\site-packages\setuptools\_distutils\cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "C:\Users\sabatini\.conda\envs\spikeinterface\lib\site-packages\setuptools\command\bdist_egg.py", line 92, in finalize_options
    ei_cmd = self.ei_cmd = self.get_finalized_command("egg_info")
  File "C:\Users\sabatini\.conda\envs\spikeinterface\lib\site-packages\setuptools\_distutils\cmd.py", line 305, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "C:\Users\sabatini\.conda\envs\spikeinterface\lib\site-packages\setuptools\_distutils\cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "C:\Users\sabatini\.conda\envs\spikeinterface\lib\site-packages\setuptools\command\egg_info.py", line 219, in finalize_options
    parsed_version = packaging.version.Version(self.egg_version)
  File "C:\Users\sabatini\.conda\envs\spikeinterface\lib\site-packages\setuptools\_vendor\packaging\version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'ibl-1.4.2'

**Comment by chris-langfield** [comment]
Hi there, this was just fixed in `1.4.3`. If you update or do a fresh clone of the repo this error should go away. Thanks!
