### ISSUE TITLE
Index error in step: learn

### ISSUE THREAD

**Issue by chris-langfield** [int-brain-lab/pykilosort#17]
Logging the issue as I look into it

```
11:29:17.240 [I] utils:557            Starting step learn.
11:31:24.337 [E] ibl:106              Error in the main loop
Traceback (most recent call last):
  File "/home/ibladmin/Documents/PYTHON/SPIKE_SORTING/pykilosort/pykilosort/ibl.py", line 99, in run_spike_sorting_ibl
    run(bin_file, dir_path=scratch_dir, output_dir=ks_output_dir, **params)
  File "/home/ibladmin/Documents/PYTHON/SPIKE_SORTING/pykilosort/pykilosort/main.py", line 177, in run
    out = learnAndSolve8b(ctx)
  File "/home/ibladmin/Documents/PYTHON/SPIKE_SORTING/pykilosort/pykilosort/learn.py", line 847, in learnAndSolve8b
    wTEMP, wPCA = extractTemplatesfromSnippets(
  File "/home/ibladmin/Documents/PYTHON/SPIKE_SORTING/pykilosort/pykilosort/learn.py", line 69, in extractTemplatesfromSnippets
    wTEMP[:, j] = cp.dot(dd[:, imax == j], amax[imax == j].T)
  File "cupy/_core/core.pyx", line 1590, in cupy._core.core._ndarray_base.__setitem__
  File "cupy/_core/_routines_indexing.pyx", line 52, in cupy._core._routines_indexing._ndarray_setitem
  File "cupy/_core/_routines_indexing.pyx", line 958, in cupy._core._routines_indexing._scatter_op
  File "cupy/_core/_routines_indexing.pyx", line 420, in cupy._core._routines_indexing._view_getitem
IndexError: Index 3 is out of bounds for axis 1 with size 3

```

**Comment by chris-langfield** [comment]
Small progress note:

Reproduced on isolated output of the preprocessing step. This bug occurs when no 1d snippets are extracted in the `extractTemplatesfromSnippets` method in `learn.py`. The nitty gritty is that `dd` is a list of empty arrays, which makes `wTEMP` empty:

https://github.com/int-brain-lab/pykilosort/blob/19f62835f725f636242f5c2edd38848c473a3c83/pykilosort/learn.py#L59C5-L59C22

which passes through the code unscathed until reaching:

https://github.com/int-brain-lab/pykilosort/blob/19f62835f725f636242f5c2edd38848c473a3c83/pykilosort/learn.py#L62-L70

Unfortunately for the dataset I'm working with this is due to the "destriped" data being all zeros. It seems that at a minimum we can say that when one or more elements of `dd` is an empty list (no peaks found), this error will occur.
