### ISSUE TITLE
Error with log file

### ISSUE THREAD

**Issue by florgf88** [int-brain-lab/pykilosort#18]
Hello! I'm trying Pykilosort for the first time. After following the installation steps, I tried to run the working example, but I'm having the following error related to the log file: 
```
(pyks2) C:\Users\Experimenter\Desktop\Scripts>python pipeline_pykilosort.py
C:\Users\Experimenter\anaconda3\envs\pyks2\lib\site-packages\ibllib\io\raw_data_loaders.py:19: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import parse_version
D:\TestpyKilosort\Raw\imec_385_100s.ap.bin: 100%|█████████| 2.31G/2.31G [03:45<00:00, 10.2MB/s]
D:\TestpyKilosort\Raw\imec_385_100s.ap.meta: 100%|████████████████| 13.9k/13.9k [00:00<00:00, 67.2kB/s]
2023-08-24 16:12:22.147 WARNING  [spikeglx.py:541] Meta data doesn't have geometry (snsShankMap/snsGeomMap field), returning defaults
Traceback (most recent call last):
  File "C:\Users\Experimenter\Desktop\Scripts\pipeline_pykilosort.py", line 30, in <module>
    run_spike_sorting_ibl(bin_file, delete=DELETE, scratch_dir=scratch_dir,
  File "c:\users\experimenter\desktop\pykilosort\pykilosort\ibl.py", line 86, in run_spike_sorting_ibl
    add_default_handler(level=log_level, filename=log_file)
  File "c:\users\experimenter\desktop\pykilosort\pykilosort\__init__.py", line 44, in add_default_handler
    handler = logging.FileHandler(filename)
  File "C:\Users\Experimenter\anaconda3\envs\pyks2\lib\logging\__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\Experimenter\anaconda3\envs\pyks2\lib\logging\__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
OSError: [Errno 22] Invalid argument: 'D:\\TestpyKilosort\\scratch\\_2023-08-24T16:12:22.149602_kilosort.log'
```
Modified script: 
```
import shutil
from pathlib import Path

from pykilosort.ibl import run_spike_sorting_ibl, ibl_pykilosort_params, download_test_data

data_path = Path("D:\TestpyKilosort\Raw")  # path on which the raw data will be downloaded
scratch_dir = Path("D:\TestpyKilosort\scratch")  # temporary path on which intermediate raw data will be written, we highly recommend a SSD drive
ks_output_dir = Path("D:\TestpyKilosort\output")  # path containing the kilosort output unprocessed
alf_path = ks_output_dir.joinpath('alf')  # this is the output standardized as per IBL standards (SI units, ALF convention)

# download the integration test data from amazon s3 bucket
bin_file, meta_file = download_test_data(data_path)

# prepare and mop up folder architecture for consecutive runs
DELETE = False  # delete the intermediate run products, if False they'll be copied over to the output directory for debugging
shutil.rmtree(scratch_dir, ignore_errors=True)
scratch_dir.mkdir(exist_ok=True)
ks_output_dir.mkdir(parents=True, exist_ok=True)

# loads parameters and run
params = ibl_pykilosort_params(bin_file)
params['Th'] = [6, 3]
run_spike_sorting_ibl(bin_file, delete=DELETE, scratch_dir=scratch_dir,
                      ks_output_dir=ks_output_dir, alf_path=alf_path, log_level='INFO', params=params)
```

I appreciate any suggestions regarding this issue, many thanks!

**Comment by chris-langfield** [comment]
Hi @florgf88 not sure if you already solved this but `:` is an invalid character in a Windows filepath, which most likely explains your error. Thanks!
